#
# Module manifest for module 'ScriptBox'
#
# Generated by: Atanas Semerdzhiev
#
# Generated on: 1.1.2015 г.
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '040a4f19-c505-4ae2-bc64-799c2a9ca78c'

# Author of this module
Author = 'Atanas Semerdzhiev'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = '(c) 2015 Atanas Semerdzhiev. All rights reserved.'

# Description of the functionality provided by this module
# Description = 'A set of useful PowerShell Scripts'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = "General.psm1", "Get-DirectoryHashes.psm1", "Transliterate.psm1", "RegEx.psm1"

# Functions to export from this module
FunctionsToExport = "Get-UniqueName",
					"Get-DirectoryHashes",
					"Import-TransliterationSchema",
					"Write-TransliterationSchema",
					"ConvertTo-TransliteratedString",
					"Rename-Transliterate",
					"Move-ItemRegex"

# Cmdlets to export from this module
# CmdletsToExport = '*'

# Variables to export from this module
# VariablesToExport = '*'

# Aliases to export from this module
# AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = "ScriptBox.psd1", "General.psm1", "Get-DirectoryHashes.psm1", "Transliterate.psm1", "RegEx.psm1"

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

